<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BlogPostSeeder extends Seeder
{
    public function run(): void
    {
        $posts = [
            [
                'user_id'      => 1,
                'title'        => '10 Tips for New Indian Immigrants in Canada',
                'slug'         => '10-tips-new-indian-immigrants-canada',
                'excerpt'      => 'Moving to Canada is exciting but comes with challenges. Here are 10 essential tips every new Indian immigrant should know.',
                'body'         => '<p>Canada welcomes thousands of Indian immigrants every year. Whether you are coming on a work permit, PR, or student visa, settling in a new country can be overwhelming.</p><h3>1. Get Your SIN Number First</h3><p>Your Social Insurance Number (SIN) is required for working and filing taxes. Apply at a Service Canada office as soon as you arrive.</p><h3>2. Open a Canadian Bank Account</h3><p>Most banks offer newcomer packages with free banking for the first year. TD, RBC, and Scotiabank all have excellent newcomer programs.</p><h3>3. Get Provincial Health Coverage</h3><p>Each province has a waiting period (usually 3 months) before provincial health insurance kicks in. Purchase private insurance in the meantime.</p><h3>4. Find Indian Grocery Stores</h3><p>Brampton, Mississauga, and Surrey have large Indian communities with plenty of desi grocery options.</p><h3>5. Join Community Groups</h3><p>Local cultural associations, temples, and community centers are great places to meet people and get support.</p>',
                'category'     => 'Immigration',
                'tags'         => json_encode(['immigration', 'canada', 'tips']),
                'status'       => 'published',
                'is_featured'  => 1,
                'views'        => 342,
                'published_at' => '2026-04-10 09:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Best Diwali Events in GTA 2026 — Complete Guide',
                'slug'         => 'best-diwali-events-gta-2026',
                'excerpt'      => 'Diwali season is here! We have compiled the best Diwali celebrations happening across the Greater Toronto Area this year.',
                'body'         => '<p>Diwali 2026 falls on October 20th and the GTA is going all out with incredible celebrations. Here is your complete guide.</p><h3>Diwali Mela in Brampton</h3><p>The biggest Diwali festival in Canada takes place at the Brampton Civic Centre. Expect live performances, fireworks, food stalls, and cultural shows.</p><h3>Mississauga Diwali Night</h3><p>Celebration Square hosts a spectacular light show every year. Free entry, live music, and hundreds of vendors.</p><h3>Toronto Diwali at Mel Lastman Square</h3><p>The city of Toronto organizes an official Diwali celebration with Bollywood performances and traditional art displays.</p>',
                'category'     => 'Events & Culture',
                'tags'         => json_encode(['diwali', 'events', 'gta']),
                'status'       => 'published',
                'is_featured'  => 1,
                'views'        => 521,
                'published_at' => '2026-04-15 10:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Understanding Canadian Credit Score — A Guide for Newcomers',
                'slug'         => 'canadian-credit-score-guide-newcomers',
                'excerpt'      => 'Building credit in Canada from scratch can be confusing. This guide explains how the Canadian credit system works and how to build a good score fast.',
                'body'         => '<p>When you arrive in Canada, you start with no credit history. This can make it difficult to rent an apartment, get a car loan, or even a credit card.</p><h3>What is a Credit Score?</h3><p>In Canada, credit scores range from 300 to 900. A score above 660 is considered good. Equifax and TransUnion are the two main credit bureaus.</p><h3>How to Start Building Credit</h3><p>Start with a secured credit card — you deposit money as collateral and use it like a regular card. Payments are reported to credit bureaus.</p><h3>Newcomer Banking Programs</h3><p>RBC, TD, and Scotiabank all offer credit cards specifically for newcomers without requiring Canadian credit history.</p>',
                'category'     => 'Finance & Banking',
                'tags'         => json_encode(['credit', 'finance', 'newcomers']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 198,
                'published_at' => '2026-04-18 11:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Top Indian Restaurants in Brampton — 2026 Community Picks',
                'slug'         => 'top-indian-restaurants-brampton-2026',
                'excerpt'      => 'Brampton has become a foodie paradise for Indian cuisine lovers. Here are the top community-recommended Indian restaurants you must try.',
                'body'         => '<p>Brampton is home to one of the largest Indian communities in Canada, and the food scene reflects that beautifully.</p><h3>Punjab Palace</h3><p>Known for their authentic tandoori dishes and best butter chicken in Brampton. The weekend lunch buffet is incredibly popular.</p><h3>Masala Junction</h3><p>A South Indian restaurant that gets the dosa and idli just right. Their sambar is as good as back home.</p><h3>Curry Kingdom</h3><p>A vegetarian-friendly spot with an extensive menu. Perfect for families with mixed dietary preferences.</p><h3>Biryani Pot</h3><p>If you are craving authentic Hyderabadi biryani, this is the place. Slow-cooked dum biryani that sells out every weekend.</p>',
                'category'     => 'Food & Dining',
                'tags'         => json_encode(['restaurants', 'brampton', 'indian-food']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 276,
                'published_at' => '2026-04-22 09:30:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'How to Transfer Money from Canada to India — Best Options in 2026',
                'slug'         => 'transfer-money-canada-to-india-2026',
                'excerpt'      => 'Sending money back home? We compare the best remittance services for Indians in Canada — rates, fees, and speed compared.',
                'body'         => '<p>Sending remittances to India is something most Indians in Canada do regularly. With so many options available, choosing the right service can save you hundreds of dollars a year.</p><h3>Wise (formerly TransferWise)</h3><p>Best exchange rates with low, transparent fees. Transfers typically arrive in 1-2 business days. Highly recommended for regular transfers.</p><h3>Remitly</h3><p>Offers an Express option (minutes) and Economy option (3-5 days). The Economy option has excellent rates.</p><h3>Western Union</h3><p>The most widely known service. Useful for recipients who can pick up cash at a local agent.</p><h3>Bank Wire Transfers</h3><p>Most expensive option but safe. RBC and TD charge $40-$50 per transfer.</p>',
                'category'     => 'Finance & Banking',
                'tags'         => json_encode(['money-transfer', 'remittance', 'india']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 445,
                'published_at' => '2026-04-25 14:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Navratri 2026 in Canada — Garba Events Near You',
                'slug'         => 'navratri-2026-canada-garba-events',
                'excerpt'      => 'Navratri season brings the community together for 9 nights of garba and dandiya. Find the best events across Canada this year.',
                'body'         => '<p>Navratri is one of the most celebrated festivals in the Indian community in Canada. The nine nights of garba and dandiya are a highlight of the cultural calendar.</p><h3>Toronto Navratri Mahotsav</h3><p>Held annually at the International Centre in Mississauga, this is one of the largest garba events in North America. Thousands attend each night.</p><h3>Brampton Garba Night</h3><p>Multiple organizations host garba nights across Brampton. Check the GoBazzar events section for the latest listings.</p><h3>Vancouver Navratri</h3><p>The BC Gujarati community hosts a week-long celebration at the Roundhouse Community Centre.</p>',
                'category'     => 'Events & Culture',
                'tags'         => json_encode(['navratri', 'garba', 'festivals']),
                'status'       => 'published',
                'is_featured'  => 1,
                'views'        => 389,
                'published_at' => '2026-04-28 10:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Getting Your Indian Driving Licence Converted in Ontario',
                'slug'         => 'indian-driving-licence-conversion-ontario',
                'excerpt'      => 'Ontario allows Indian drivers to exchange their licence under certain conditions. Here is a step-by-step guide to the process.',
                'body'         => '<p>If you hold an Indian driving licence, you may be able to convert it to an Ontario licence without taking a full road test.</p><h3>Eligibility</h3><p>Ontario has a reciprocal agreement with certain countries. Indian licence holders must pass a G1 written test and G2 road test.</p><h3>Documents Required</h3><p>You will need your original Indian licence, passport, proof of Ontario residency, and the application fee.</p><h3>Step-by-Step Process</h3><p>Visit a DriveTest centre with all documents. Pay the $158.25 fee, pass the G1 written knowledge test, and then book your G2 road test.</p><h3>Tips for Passing</h3><p>Study the Ontario Drivers Handbook thoroughly. Pay special attention to right of way, school bus rules, and winter driving regulations.</p>',
                'category'     => 'Driving & Transport',
                'tags'         => json_encode(['driving', 'licence', 'ontario']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 312,
                'published_at' => '2026-05-01 09:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Holi Festival Highlights 2026 — Canada Celebrates in Colour',
                'slug'         => 'holi-festival-highlights-2026-canada',
                'excerpt'      => 'Holi 2026 was celebrated with great enthusiasm across Canada. Here are the highlights from events in Toronto, Vancouver, Calgary, and more.',
                'body'         => '<p>Holi, the festival of colours, was celebrated with incredible energy across Canadian cities in 2026.</p><h3>Vancouver Holi Festival</h3><p>The Holi Festival of Colours at Sunset Beach drew over 5,000 people. The event featured live Bhangra performances, colour throws every hour, and street food stalls.</p><h3>Toronto Colour Run</h3><p>A combination of Holi celebration and 5km colour run at Downsview Park. Families and students all participated.</p><h3>Calgary Holi Dhulandi</h3><p>The Gujarati Samaj of Calgary organized a traditional Holi celebration with organic colours, folk music, and Gujarati snacks.</p>',
                'category'     => 'Events & Culture',
                'tags'         => json_encode(['holi', 'festivals', 'canada']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 267,
                'published_at' => '2026-05-05 11:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
            [
                'user_id'      => 1,
                'title'        => 'Indian Students in Canada — Scholarships and Part-Time Work Guide',
                'slug'         => 'indian-students-canada-scholarships-work-guide',
                'excerpt'      => 'Are you an Indian student planning to study in Canada? Here is everything you need to know about scholarships, part-time work rules, and settling in.',
                'body'         => '<p>Canada is one of the top destinations for Indian students. With world-class universities and post-study work opportunities, it is easy to see why.</p><h3>Scholarships Available</h3><p>Vanier Canada Graduate Scholarships, Ontario Graduate Scholarship, and university-specific merit scholarships are available. Apply early as deadlines vary.</p><h3>Part-Time Work Rules</h3><p>International students can work up to 24 hours per week during academic sessions and full-time during scheduled breaks. Your study permit must allow work on campus.</p><h3>Post-Graduation Work Permit (PGWP)</h3><p>After completing a program of at least 8 months, you can apply for a PGWP that allows you to work in Canada for up to 3 years.</p><h3>Student Communities</h3><p>Most universities have active Indian Student Associations. These are great for networking, cultural events, and getting settled.</p>',
                'category'     => 'Education',
                'tags'         => json_encode(['students', 'scholarships', 'study-permit']),
                'status'       => 'published',
                'is_featured'  => 0,
                'views'        => 410,
                'published_at' => '2026-05-06 10:00:00',
                'created_at'   => now(),
                'updated_at'   => now(),
            ],
        ];

        DB::table('blog_posts')->insert($posts);
    }
}
